# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/rprogram/version.rb'

Hoe.new('rprogram', RProgram::VERSION) do |p|
  p.rubyforge_name = 'rprogram'
  p.author = 'Postmodern Modulus III'
  p.email = 'postmodern.mod3@gmail.com'
  p.summary = 'RProgram is a library for creating Rubyful wrappers around command-line programs'
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
end

# vim: syntax=Ruby
